-- MySQL Script generated by MySQL Workbench
-- Mon Aug  8 22:56:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `telefone` INT NULL,
  `email` VARCHAR(45) NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente_endereco` (
  `cod_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` INT NULL,
  `logradouro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `complementos` VARCHAR(45) NULL,
  `data_cadastro` DATETIME NULL,
  `tb_cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`cod_endereco`, `tb_cliente_cpf`),
  INDEX `fk_tb_cliente_endereco_tb_cliente_idx` (`tb_cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_endereco_tb_cliente`
    FOREIGN KEY (`tb_cliente_cpf`)
    REFERENCES `mydb`.`tb_cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `cod_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor_minimo` DECIMAL(8,2) NULL,
  `taxa_referencia` DECIMAL(8,2) NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_conta` (
  `cod_conta` INT NOT NULL,
  `agencia` INT NULL,
  `banco` INT NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`cod_conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_transacao` (
  `cod_transacao` INT NOT NULL AUTO_INCREMENT,
  `data_transacao` DATETIME NULL,
  `valor` DECIMAL(8,2) NULL,
  `tipo_transacao` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_transacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto_aquisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto_aquisicao` (
  `cod_produto_aquisicao` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(8,2) NULL,
  `data_aquisicao` DATETIME NULL,
  `tb_conta_cod_conta` INT NOT NULL,
  `tb_produto_cod_produto` INT NOT NULL,
  `tb_transacao_cod_transacao` INT NOT NULL,
  PRIMARY KEY (`cod_produto_aquisicao`),
  INDEX `fk_tb_produto_aquisicao_tb_conta1_idx` (`tb_conta_cod_conta` ASC) VISIBLE,
  INDEX `fk_tb_produto_aquisicao_tb_produto1_idx` (`tb_produto_cod_produto` ASC) VISIBLE,
  INDEX `fk_tb_produto_aquisicao_tb_transacao1_idx` (`tb_transacao_cod_transacao` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_aquisicao_tb_conta1`
    FOREIGN KEY (`tb_conta_cod_conta`)
    REFERENCES `mydb`.`tb_conta` (`cod_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_aquisicao_tb_produto1`
    FOREIGN KEY (`tb_produto_cod_produto`)
    REFERENCES `mydb`.`tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_aquisicao_tb_transacao1`
    FOREIGN KEY (`tb_transacao_cod_transacao`)
    REFERENCES `mydb`.`tb_transacao` (`cod_transacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente_has_tb_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente_has_tb_conta` (
  `tb_cliente_cpf` INT NOT NULL,
  `tb_conta_cod_conta` INT NOT NULL,
  PRIMARY KEY (`tb_cliente_cpf`, `tb_conta_cod_conta`),
  INDEX `fk_tb_cliente_has_tb_conta_tb_conta1_idx` (`tb_conta_cod_conta` ASC) VISIBLE,
  INDEX `fk_tb_cliente_has_tb_conta_tb_cliente1_idx` (`tb_cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_has_tb_conta_tb_cliente1`
    FOREIGN KEY (`tb_cliente_cpf`)
    REFERENCES `mydb`.`tb_cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cliente_has_tb_conta_tb_conta1`
    FOREIGN KEY (`tb_conta_cod_conta`)
    REFERENCES `mydb`.`tb_conta` (`cod_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
